### ISSUE TITLE
Choosing the software license for the main repository

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2020-2021#11]
Hi @open-sci/grasshoppers and @open-sci/the-leftovers-2-0,

As anticipated in [yesterday's lecture (practical part)](https://docs.google.com/presentation/d/1LHPGt18AhFF-VkzQljlsiADWCnWvzy-I6ZoMDNtJMqo/edit#slide=id.gcd92ad6878_0_33), we have to specify the license for all the software available in our [main repository](https://github.com/open-sci/2020-2021/). My preference would be to use the [ISC license](https://opensource.org/licenses/ISC) but I am happy to use another one if you think it is more appropriate for our course.

What do you think? Please start a discussion as comments on this issue.

**Comment by arcangelo7** [comment]
I have read several Open Source Licenses and, from what I understand, there are two types: the permissive ones (Apache License 2.0, BSD, MIT license, ISC) and the ones with the copyleft (GPL). Assuming that I had a hard time finding substantial differences between the various permissive licenses, to be honest, I like the Apache License 2.0 more than the ISC, because the former is more explicit about what it means by every single term used, such as "License", "Licensor", "Legal Entity" and " You ". 

However, in general, the GPL license seems to be the one that takes the concept of open-source more seriously, ensuring that every single redistribution of the source remains open-source. That way, even if a derivative work is distributed for a fee, by the time someone legally comes into possession of that product, the code would have to be released under the GPL. For this reason, I imagine the GPL is less popular than the other licenses, as it restricts the potential users of the software. However, this kind of limitation seems ethical to me, and since Science and Openness are the focus for this course, it seems that GPL would be a more relevant choice as a license.

**Comment by NoonShin** [comment]
I personally would prefer less prolix and more compact licenses. The GPL-3.0 or the Apache-2.0 both have long-winded documentations which might, at first glance at least, seem frightful in the legal aspect to the potential user of the software. Arcangelo is correct to mention that the Apache-2.0 is more explicit in its definitions, but I believe the mere compatibility of other, shorter licenses (such as MIT and ISC) to the GPLv3 can be a clear enough pointer to their being reliable free software licenses. Overall, I find the text of the [MIT license](https://opensource.org/licenses/MIT) to be the most succinct one, but I'm also partial to the ISC and the [BSD-2-Clause](https://opensource.org/licenses/BSD-2-Clause). If we're going with copyleft, though, the [GPL-3.0](https://opensource.org/licenses/GPL-3.0) itself would probably be our safest bet.

**Comment by sntcristian** [comment]
I personally prefer licenses that just ensure authorship attribution without putting too much restrictions on further distribution, but I think it's a matter of personal taste. Among the "permissive licenses", I think that Apache is too verbose and the add-on that it has with respect to patents is out of the scope of our researches. Thus, I would go with the shorter ones, such as MIT or ISC.

**Comment by essepuntato** [comment]
What do the others think about it? We should reach a decision today.

**Comment by saroppini** [comment]
I agree with Nooshin and Cristian. I would prefer MIT or ISC for the reasons they explained clearly, and also because I think they are the most suitable since we should choose a license that maximizes the software reuse (i.e. with limited constraints). They are also very clear and straightforward.

**Comment by Alessia438** [comment]
I agree too with Nooshin and Cristian about choosing a license with a short and clear documentation. Therefore also for me both MIT or ISC are good choices, since they also are well known and permissive licenses.

**Comment by denizovski** [comment]
As far as I have read those licenses, with the GPL, anyone who touches open-source codes is granted the right to use, modify, develop, copy, put up for sale, and distribute the codes in an unlimited way. However, other software to be derived from a GPL licensed software must also be offered or distributed under a GPL license. In this respect, GPL promotes open-source software and attaches importance to collective effort and cooperation for development. In this case, the GPL can be safe and appropriate. But at the same time, the MIT license is a functional license type developed by the Massachusetts Institute of Technology, which is the most widely used in the world. The MIT license frees us on many issues. While my priority is GPL, MIT is also suitable.

**Comment by ariannamorettj** [comment]
As my colleagues proposed, I'd suggest to choose a license which is as clear and concise as possible, while staying permissive too. Since ISC and MIT are very close for their purposes and their differences don't seem to be so relevant in their factual application, I'd personally choose ISC because it is expressed with unequivocal language and therefore it can be understood by anyone, also with none or a very limited knowledge of the undelying legal background. 
However, MIT license makes explicit mention of sublicensing too,  while ISC doesn't. Further, the slightly more complex structure of MIT could - to some extent - also facilitate the resolution of some doubts that could araise in particular circumstances. 
For these reasons, even if I personally prefer ISC license, I totally agree to adopt also MIT.

**Comment by arcangelo7** [comment]
It seems that most people agreed on using ISC. Although I would prefer GPL, ISC also appears to be a valid solution. If you agree, I can close this issue and upload the ISC license.
